config/routes.rb
Rails.application.routes.draw do
  resources :homes
  resources :categoria
  devise_for :users 
  #resources :saidas
  resources :entradas
  #devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categorium.rb
class Categorium < ApplicationRecord
    has_many :entradas, dependent: :destroy
    has_many :saidas, dependent: :destroy
    validates :descricao, presence: true, length: { minimum: 5 }
end

app/models/entrada.rb
class Entrada < ApplicationRecord
  belongs_to :user
  belongs_to :categoria
  validates :descricao, presence: true, length: { minimum: 5 }
  validates :vencimento, presence: true
  validates :valorPlanejado, presence: true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/saida.rb
class Saida < ApplicationRecord
  belongs_to :user
  belongs_to :categoria
  validates :descricao, presence: true, length: { minimum: 5 }
  validates :vencimento, presence: true
  validates :valorPlanejado, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :entradas, dependent: :destroy
  has_many :saidas, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  allow_browser versions: :modern
end

app/controllers/categoria_controller.rb
class CategoriaController < ApplicationController
  before_action :set_categorium, only: %i[ show edit update destroy ]

  # GET /categoria or /categoria.json
  def index
    @categoria = Categorium.all
    @categorianovo = Categorium.new
  end

  # GET /categoria/1 or /categoria/1.json
  def show
  end

  # GET /categoria/new
  def new
    @categoria = Categorium.new
  end

  # GET /categoria/1/edit
  def edit
  end

  # POST /categoria or /categoria.json
  def create
    @categorium = Categorium.new(categorium_params)

    respond_to do |format|
      if @categorium.save
        format.html { redirect_to categorium_url(@categorium), notice: "Categorium was successfully created." }
        format.json { render :show, status: :created, location: @categorium }
      else
        format.html { render :new, status: :unprocessable_entity, notice: "Categorium was successfully created." }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categoria/1 or /categoria/1.json
  def update
    respond_to do |format|
      if @categorium.update(categorium_params)
        format.html { redirect_to categorium_url(@categorium), notice: "Categorium was successfully updated." }
        format.json { render :show, status: :ok, location: @categorium }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoria/1 or /categoria/1.json
  def destroy
    @categorium.destroy!

    respond_to do |format|
      format.html { redirect_to categoria_url, notice: "Categorium was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categorium
      @categorium = Categorium.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def categorium_params
      params.require(:categorium).permit(:descricao)
    end
end

app/controllers/entradas_controller.rb
class EntradasController < ApplicationController
  before_action :set_entrada, only: %i[ show edit update destroy ]
  def index
    @entradas = Entrada.all
  end

  def show
  end

  def new
    @entrada = current_user.entradas.new
  end

  def edit
  end

  def create
    @entrada = current_user.entradas.new(entrada_params)

    respond_to do |format|
      if @entrada.save
        format.html { redirect_to entrada_url(@entrada), notice: "Entrada was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }

      end
    end
  end

  def update
    respond_to do |format|
      if @entrada.update(entrada_params)
        format.html { redirect_to entrada_url(@entrada), notice: "Entrada was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @entrada.destroy!

    respond_to do |format|
      format.html { redirect_to entradas_url, notice: "Entrada was successfully destroyed." }
    end
  end

  private

    def set_entrada
      @entrada = Entrada.find(params[:id])
    end

    def entrada_params
      params.require(:entrada).permit(:valorPlanejado, :valorTotal, :valorTaxa, :vencimento, :descricao)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: %i[ show edit update destroy ]

  # GET /homes or /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1 or /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes or /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to home_url(@home), notice: "Home was successfully created." }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1 or /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to home_url(@home), notice: "Home was successfully updated." }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1 or /homes/1.json
  def destroy
    @home.destroy!

    respond_to do |format|
      format.html { redirect_to homes_url, notice: "Home was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def home_params
      params.fetch(:home, {})
    end
end

app/controllers/saidas_controller.rb
class SaidasController < ApplicationController
  before_action :set_saida, only: %i[ show edit update destroy ]

  def index
    @saidas = Saida.all
  end

  def show
  end

  def new
    @saida = Saida.new
  end

  def edit
  end

  def create
    @saida = Saida.new(saida_params)

    respond_to do |format|
      if @saida.save
        format.html { redirect_to saida_url(@saida), notice: "Saida was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @saida.update(saida_params)
        format.html { redirect_to saida_url(@saida), notice: "Saida was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @saida.destroy!

    respond_to do |format|
      format.html { redirect_to saidas_url, notice: "Saida was successfully destroyed." }
    end
  end

  private
    def set_saida
      @saida = Saida.find(params[:id])
    end

    def saida_params
      params.require(:saida).permit(:valorPlanejado, :valorTotal, :valorTaxa, :vencimento, :descricao)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/entradas_helper.rb
module EntradasHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/saidas_helper.rb
module SaidasHelper
end

app/views/categoria/_categorium.html.erb
<div id="<%= dom_id categorium %>">
  <p>
    <strong>Descricao:</strong>
    <%= categorium.descricao %>
  </p>

</div>

app/views/categoria/_form.html.erb
<%= simple_form_for (@categorianovo)do |f| %>
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="form-inputs">
<%= f.input :descricao %>
</div>

<div class="form-actions">
<div class="modal-footer">
<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
<%= f.button :submit, class:"btn btn-primary"%>

app/views/categoria/edit.html.erb
<% content_for :title, "Editing categorium" %>

<h1>Editing categorium</h1>

<%= render "form", categorium: @categorium %>

<br>

<div>
  <%= link_to "Show this categorium", @categorium %> |
  <%= link_to "Back to categoria", categoria_path %>
</div>

app/views/categoria/index.html.erb
<h1>Categories</h1>

<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
  Novo
</button>

<table class="table table-striped table-hover table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>description</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @categoria.each do |categorium| %>
    <tr>
      <td><%= categorium.id %></td>
      <td><%= categorium.descricao %></td>
      <td>
         <%= link_to "Edit", edit_categorium_path(categorium), class: 'btn btn-primary' %>  |
         
         <%= link_to "Destroy", categorium, method: :delete, class: 'btn btn-danger'%>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<br>


<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasRightLabel">Categoria</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    ...
  </div>
</div>
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
 <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">Novo</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <%= simple_form_for @categorianovo do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

          <div class="form-inputs">
            <%= f.input :descricao %>
          </div>

          <div class="form-actions">
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <%= f.button :submit, class:"btn btn-primary" %>
          </div>
      </div>
        <% end %>
      </div>
      
    </div>
  </div>
</div>

app/views/entradas/_form.html.erb
<%= simple_form_for(@entrada )do |form| %>
  <%= form.input :descricao %>
  <%= form.input :valorPlanejado %>
  <%= form.input :vencimento, as: :date, html5: true %>

  <br>
  <p>
    <%= form.button :submit, class: 'btn btn-primary' %>
  </p>
<% end %>

app/views/entradas/index.html.erb
 <%= link_to "Novo Lancamento", new_entrada_path, class: 'btn btn-primary' %>
    
<%= render @entradas%>

app/views/entradas/new.html.erb
<h1>Novo</h1>
<%= render "form", entrada: @entradas %>

app/views/homes/_form.html.erb
<%= simple_form_for(@home) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/homes/_home.html.erb
<div id="<%= dom_id home %>">
</div>

app/views/homes/edit.html.erb
<% content_for :title, "Editing home" %>

<h1>Editing home</h1>

<%= render "form", home: @home %>

<br>

<div>
  <%= link_to "Show this home", @home %> |
  <%= link_to "Back to homes", homes_path %>
</div>

app/views/homes/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Homes" %>

<h1>Homes</h1>

<div id="homes">
  <% @homes.each do |home| %>
    <%= render home %>
    <p>
      <%= link_to "Show this home", home %>
    </p>
  <% end %>
</div>

<%= link_to "New home", new_home_path %>

app/views/homes/new.html.erb
<% content_for :title, "New home" %>

<h1>New home</h1>

<%= render "form", home: @home %>

<br>

<div>
  <%= link_to "Back to homes", homes_path %>
</div>

app/views/homes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @home %>

<div>
  <%= link_to "Edit this home", edit_home_path(@home) %> |
  <%= link_to "Back to homes", homes_path %>

  <%= button_to "Destroy this home", @home, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Contas" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta http-equiv="refresh" content="50" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   
    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <p class="notice"><%= notice %></p> 
   <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>